spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/school_db'
    username: postgres
    password: postgres
  jpa:
    show-sql: true
  flyway:
    enabled: true
    schemas: public
    locations: 'classpath:consoleapp/db/migration'
